# Node.js 18 이미지를 기반으로 사용
FROM node:18

# NestJS 앱의 작업 디렉토리 설정
WORKDIR /app

# package.json과 lock 파일 복사 → 캐시 최적화
COPY package*.json ./

# 의존성 설치
RUN npm install

# 나머지 소스 코드 복사
COPY . .

# NestJS 앱 빌드
RUN npm run build

# NestJS 프로덕션 서버 실행
CMD ["npm", "run", "start:prod"]
